"""Remove address table

Revision ID: ac28efadd84c
Revises: e88e821ce720
Create Date: 2024-08-21 11:23:29.702050

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac28efadd84c'
down_revision: str | None = 'e88e821ce720'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_address_id_fkey', 'patient', type_='foreignkey')
    op.drop_constraint('prescriber_office_address_id_fkey', 'prescriber', type_='foreignkey')
    op.drop_table('address')
    op.add_column('patient', sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('state', sa.Enum('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', name='state'), nullable=False))
    op.add_column('patient', sa.Column('zipcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('patient', 'address_id')
    op.add_column('prescriber', sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('prescriber', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('prescriber', sa.Column('state', sa.Enum('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', name='state'), nullable=False))
    op.add_column('prescriber', sa.Column('zipcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('prescriber', 'office_address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriber', sa.Column('office_address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('prescriber_office_address_id_fkey', 'prescriber', 'address', ['office_address_id'], ['id'])
    op.drop_column('prescriber', 'zipcode')
    op.drop_column('prescriber', 'state')
    op.drop_column('prescriber', 'city')
    op.drop_column('prescriber', 'street')
    op.add_column('patient', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patient_address_id_fkey', 'patient', 'address', ['address_id'], ['id'])
    op.drop_column('patient', 'zipcode')
    op.drop_column('patient', 'state')
    op.drop_column('patient', 'city')
    op.drop_column('patient', 'street')
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', name='state'), autoincrement=False, nullable=False),
    sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey')
    )
    # ### end Alembic commands ###
