"""Remove primary prescriber field

Revision ID: dd7dc96d6cbb
Revises: 1088bd0d18d7
Create Date: 2024-08-23 11:23:43.311763

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd7dc96d6cbb'
down_revision: str | None = '1088bd0d18d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_primary_care_prescriber_id_fkey', 'patient', type_='foreignkey')
    op.drop_column('patient', 'primary_care_prescriber_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('primary_care_prescriber_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patient_primary_care_prescriber_id_fkey', 'patient', 'prescriber', ['primary_care_prescriber_id'], ['id'])
    # ### end Alembic commands ###
