"""Remove insurance table and put fields in patient

Revision ID: e88e821ce720
Revises: 5f7924b7cafa
Create Date: 2024-08-21 10:54:15.400486

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e88e821ce720'
down_revision: str | None = '5f7924b7cafa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patients_insurance_id_fkey', 'patient', type_='foreignkey')
    op.drop_table('insurance')
    op.add_column('patient', sa.Column('member_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('insurance_group_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('insurance_rx_bin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('insurance_rx_pcn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('insurance_person_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('patient', 'insurance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('insurance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patients_insurance_id_fkey', 'patient', 'insurance', ['insurance_id'], ['id'])
    op.drop_column('patient', 'insurance_person_code')
    op.drop_column('patient', 'insurance_rx_pcn')
    op.drop_column('patient', 'insurance_rx_bin')
    op.drop_column('patient', 'insurance_group_number')
    op.drop_column('patient', 'member_id_number')
    op.create_table('insurance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_bin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_pcn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('person_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='insurance_info_pkey')
    )
    # ### end Alembic commands ###
