"""Add country to Address

Revision ID: fe982c218f5c
Revises: f4d7ae2ea20b
Create Date: 2024-04-23 13:47:23.706033

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fe982c218f5c"
down_revision: str | None = "f4d7ae2ea20b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "country")
    # ### end Alembic commands ###
